"""add first name and last name to students table

Revision ID: 60859f6a406b
Revises: 32229d31bdd3
Create Date: 2024-03-14 00:28:55.283041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60859f6a406b'
down_revision: Union[str, None] = '32229d31bdd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students") as batch_op:
        batch_op.drop_column('name')

    # op.drop_column('students', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students") as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
    # op.add_column('students', sa.Column('name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
