"""add course id to students table

Revision ID: bb153f4d18f4
Revises: bb98e46176bb
Create Date: 2024-03-14 01:08:27.972100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb153f4d18f4'
down_revision: Union[str, None] = 'bb98e46176bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students") as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_students_courses", "courses",['course_id'],['id'])
    # op.add_column('students', sa.Column('course_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'students', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students") as batch_op:
        batch_op.drop_constraint(None,"students", type_="foreignKey")
        batch_op.drop_column('course_id')

    # op.drop_constraint(None, 'students', type_='foreignkey')
    # op.drop_column('students', 'course_id')
    # ### end Alembic commands ###
