"""rename first name column in students table

Revision ID: f976e449e7bb
Revises: 60859f6a406b
Create Date: 2024-03-14 00:33:16.439916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f976e449e7bb'
down_revision: Union[str, None] = '60859f6a406b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students") as batch_op:
        batch_op.add_column(sa.Column('real_first_name', sa.String(), nullable=True))
        batch_op.drop_column('first_name')
    # op.add_column('students', sa.Column('real_first_name', sa.String(), nullable=True))
    # op.drop_column('students', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students") as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('real_first_name')
    # op.add_column('students', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    # op.drop_column('students', 'real_first_name')
    # ### end Alembic commands ###
